#ifndef TLV_CPP
#define TLV_CPP

#include <stdio.h>
#include <vector>
#include <stdint.h>
#include <string.h>

enum tlv_type {
    TLV_TYPE_MEM_TOTAL = 1,
    TLV_TYPE_MEM_FREE,
    TLV_TYPE_MEM_AVAILABLE,
    TLV_TYPE_BUFFERS,
    TLV_TYPE_CACHED,
    TLV_TYPE_SWAP_CACHED,
    TLV_TYPE_ACTIVE,
    TLV_TYPE_INACTIVE,
    TLV_TYPE_ACTIVE_ANON,
    TLV_TYPE_INACTIVE_ANON,
    TLV_TYPE_ACTIVE_FILE,
    TLV_TYPE_INACTIVE_FILE,
    TLV_TYPE_UNEVICTABLE,
    TLV_TYPE_MLOCKED,
    TLV_TYPE_HIGH_TOTAL,
    TLV_TYPE_HIGH_FREE,
    TLV_TYPE_LOW_TOTAL,
    TLV_TYPE_LOW_FREE,
    TLV_TYPE_SWAP_TOTAL,
    TLV_TYPE_SWAP_FREE,
    TLV_TYPE_DIRTY,
    TLV_TYPE_WRITEBACK,
    TLV_TYPE_ANON_PAGES,
    TLV_TYPE_MAPPED,
    TLV_TYPE_SHMEM,
    TLV_TYPE_SLAB,
    TLV_TYPE_S_RECLAIMABLE,
    TLV_TYPE_S_UNRECLAIM,
    TLV_TYPE_KERNEL_STACK,
    TLV_TYPE_PAGE_TABLES,
    TLV_TYPE_NFS_UNSTABLE,
    TLV_TYPE_BOUNCE,
    TLV_TYPE_WRITEBACK_TMP,
    TLV_TYPE_COMMIT_LIMIT,
    TLV_TYPE_COMMITTED_AS,
    TLV_TYPE_VMALLOC_TOTAL,
    TLV_TYPE_VMALLOC_USED,
    TLV_TYPE_VMALLOC_CHUNK,

    TLV_TYPE_WIFI_ADDR,
    TLV_TYPE_WIFI_AID,
    TLV_TYPE_WIFI_CHAN,
    TLV_TYPE_WIFI_TXRATE,
    TLV_TYPE_WIFI_RXRATE,
    TLV_TYPE_WIFI_RSSI,
    TLV_TYPE_WIFI_MIN_RSSI,
    TLV_TYPE_WIFI_MAX_RSSI,
    TLV_TYPE_WIFI_IDLE,
    TLV_TYPE_WIFI_TXSEQ,
    TLV_TYPE_WIFI_RXSEQ,
    TLV_TYPE_WIFI_CAPS,
    TLV_TYPE_WIFI_XCAPS,
    TLV_TYPE_WIFI_ACAPS,
    TLV_TYPE_WIFI_ERP,
    TLV_TYPE_WIFI_STATE,
    TLV_TYPE_WIFI_MAXRATE_DOT11,
    TLV_TYPE_WIFI_HTCAPS,
    TLV_TYPE_WIFI_VHTCAPS,
    TLV_TYPE_WIFI_ASSOC_TIME,
    TLV_TYPE_WIFI_IES,
    TLV_TYPE_WIFI_MODE,
    TLV_TYPE_WIFI_RXNSS,
    TLV_TYPE_WIFI_TXNSS,
    TLV_TYPE_WIFI_PSMODE,
    TLV_TYPE_WIFI_MIN_TX_POWER,
    TLV_TYPE_WIFI_MAX_TX_POWER,
    TLV_TYPE_WIFI_HT_CAPABLE,
    TLV_TYPE_WIFI_VHT_CAPABLE,
    TLV_TYPE_WIFI_MU_CAPABLE,
    TLV_TYPE_WIFI_SNR,
    TLV_TYPE_WIFI_OPERATING_BAND,
    TLV_TYPE_WIFI_CURRENT_OPERATING_CLASS,
    TLV_TYPE_WIFI_SUPPORTED_OPERATING_CLASSES,
    TLV_TYPE_WIFI_SUPPORTED_OPERATING_CLASSES_COUNT,
    TLV_TYPE_WIFI_SUPPORTED_RATES,
    TLV_TYPE_WIFI_SUPPORTED_RATES_COUNT,
    TLV_TYPE_WIFI_MAX_STA_PHYMODE,

    TLV_TYPE_WIFI_STATION_LIST,
    TLV_TYPE_WIFI_VAP,
    TLV_TYPE_WIFI_VAP_NAME,
    TLV_TYPE_WIFI_STATION,

    // TLV_TYPE_WIFI_STUB_VAP_COUNT,
    // TLV_TYPE_WIFI_STUB_VAP_INDEX,
    // TLV_TYPE_WIFI_STUB_CLIENTS_COUNT,
    // TLV_TYPE_WIFI_STUB_CLIENT_INDEX,
    // TLV_TYPE_WIFI_STUB_CLIENT_VAL1,
    // TLV_TYPE_WIFI_STUB_CLIENT_VAL2,
    // TLV_TYPE_WIFI_STUB_CLIENT_VAL3
};

struct tlv_packet {
    uint8_t type;
    uint16_t length;
    std::vector<uint8_t> value;
};

tlv_packet build(uint8_t type, const char* value);
void serialize_tlv(std::vector<uint8_t>& serialized, tlv_packet packet);
void serialize_tlv_container(std::vector<uint8_t>& out, uint8_t type, const std::vector<uint8_t>& value);
const char* tlv_type_to_char(enum tlv_type type);
void deserialize_tlv(const uint8_t *payload, int payloadlen, struct tlv_packet* serialized, int *packets_count );
#endif // TLV_CPP
